server:
  port: 8090
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb # use an in-memory H2 database called testdb
    driver-class-name: org.h2.Driver # use the H2 JDBC driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true # enable the H2 console logs
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create the tables if they don't exist automatically when the application starts
    show-sql: true # show the SQL queries in the console logs
springdoc:
  swagger-ui:
    path: /docs # the URL path to access the Swagger UI